{% set name = "astroscrappy" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5480d7ff87eb3aaf400f8fde389a299f21a3b7fff4c1ba4c0795a09fbbad5f71
  patches:
    - setup.cfg.patch

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - astropy
    - cython
    - numpy 1.13.*  # [py35]
    - numpy 1.13.*  # [py36]
    - numpy 1.14.*  # [py>=37]
  run:
    - python
    - astropy
    - numpy >=1.13.*  # [py35]
    - numpy >=1.13.*  # [py36]
    - numpy >=1.14.*  # [py>=37]

test:
  # Python imports
  imports:
    - astroscrappy
    - astroscrappy.tests
    - astroscrappy.utils

about:
  home: https://github.com/astropy/astroscrappy
  license: BSD-3-clause
  license_family: BSD
  license_file: licenses/LICENSE.rst
  summary: 'Speedy Cosmic Ray Annihilation Package in Python'
  description: |
      Astro-SCRAPPY is designed to detect cosmic rays in images
      (numpy arrays), originally based on Pieter van Dokkum’s L.A.Cosmic
      algorithm.
  dev_url: https://github.com/astropy/astroscrappy

extra:
  recipe-maintainers:
    - mwcraig
