{% set name = "astroscrappy" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e196c7ce839b4b2fa8ddba8f75c1a1ee45ff1247d01e8c8e7b4debf6974156a

build:
  number: 4
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    # numpy 1.25 introduced the backwards compatible ABI
    - numpy >=1.25 ,<2                        # [build_platform != target_platform and py<310]
    - numpy >=2.0                            # [build_platform != target_platform and py>=310]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip !=22.1
    - astropy
    - cython >=3.0,<4.0a0
    # numpy 1.25 introduced the backwards compatible ABI
    - numpy >=1.25,<2                           # [py<310]
    - numpy >=2.0                            # [py>=310]
    - extension-helpers
    - setuptools_scm
  run:
    - python
    - astropy
    - numpy >=1.23

test:
  # Python imports
  imports:
    - astroscrappy
    - astroscrappy.tests
    - astroscrappy.utils

about:
  home: https://github.com/astropy/astroscrappy
  license: BSD-3-Clause
  license_family: BSD
  license_file: licenses/LICENSE.rst
  summary: Speedy Cosmic Ray Annihilation Package in Python
  description: |
    Astro-SCRAPPY is designed to detect cosmic rays in images
    (numpy arrays), originally based on Pieter van Dokkum’s L.A.Cosmic
    algorithm.
  dev_url: https://github.com/astropy/astroscrappy

extra:
  recipe-maintainers:
    - mwcraig
