appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: kYEwtO2XXmpxAfzDVAIL2az8pY+eO28ApmiKspA1oChMwiqD90PPOvW9UU9gxON5PeR7SsoazKE76wudjt+rDbghJLGUox5oDnjXIdlCohbI5IEpm8wnIGw/1mqWw4M5PN1ZsVacuOZ8OVrtVWqlQ+TjwDgJbz6LGxTqnj+LWBb8XgMgoTCAmH+J0vMAzeC1wA87IrRyT1MU/MsBynBl9YWm+p8b4d1vANcUuiKaSwNm5EdqC3/qbDZu7g8dShxmyZP2QeYXAADeshzTD+fLZpYObcFFpY3wdD7H2HaR0M/VnT/25VfCWKxIgryHuopOpbbGOVC78xt3cqL9PrEpsV03X+IsE3iugu4yAdxcYo6n0SkWOenm7EKHauZBDuG2PBuorF5Ul5BIyESJzYqIPMP/0mCdaTV1TbYyBLgktTvU5RtcN1nxM03knuI+mIIsSkz9zNrKIsBnVtvMpO8lSQXpjQ0ZEBpxgcjjTXQ9WA2uYSiO6VYRc2SAS4tEfytywZR8zZ2hd7mAWVjz4HPkEjBvZ7cGDqjmDMnWTt4ou80ya9A6YnpPdWxSeSQT3kTlyHfpx27MSCw/7Vcflcc6OKucIqtmVs6Krq2moa1hyAeFPF7r2AGz0jwuUkC+F6+Cuu8fEEad7hWqjxkMl1sskCA/m0i6BYAZXuOzcRbbNcA=}
provider:
  win: azure
conda_forge_output_validation: false
