travis:
  secure:
    BINSTAR_TOKEN: Po5Wq6FYks14DKFBbb086U4YthCeW8WAjvSnOb7r2kZFIHqRXi7faYOxoeXk6DasNlD6UQyASc4dFWOUow+42EsMG92LOuRCzcHBO29jlFJnUdj0n38u/bHgRz5nkAEdFqp03v5i1mXcW50n26UBNJ4E0DelD2FphVSeS3t+PVFBUFzmfl/ibBQL76lKICb35dDBvXFV/q/hB5Xish3wDurGq+UF/K2OA8B47B8yPDZZi3WQZAbYx9uXNgSiOaz2wsY4pIWuySrcfF0j9kOfbnNGaSATwIJ+zY2jmlZQSLpuyZEKFAO8Gp12hwn3VsH7qFPIpPkdr7cXkgbp0sj6SeiJt0Cte8N6uCxXJjUY6plBhZdOlzJgOm+nRxwvC59VluU7F/bTHeWn+EYjr0lgyaPil2M/HAt+WnxVV37X998AkeU/YezNzyCrSo1JzRipW7AHrCq0IYI3jjJgm3gy9o90tJjGcW+N66LZC6+6UFPNiqVebTQhyuawcvzf9UV5f3lzdizfmPsAZF9DlEpuqlk/jLFgPCP3rZvJ0WcauqcsyXtCOGOwgOYYpj0RqgTFu0hDBwOPL/vgGflcV2qptChkGB8RvCdMmukp+aCXyjKit1NlK/Zxo7F4xoCjQxMIHJ0eaWMa56Xt3zdbMdnSFEWAZfOxg2SosM9pAsrx1mg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
