travis:
  secure:
    BINSTAR_TOKEN: xzRNHihFnzBAXjXjyVM3R17K1NLP1jexzfibKslgliTRjpg6zdLW7qr/TDVDpzMvd59UWMSf0Y1gXgjt/aNA9zP21vXlu4L7qrSY18fhlR1tGSUr6SgDLpURvtV4ft5BoAq9WtWEm7p1UtFVVFnXnmYBlOoCX9usM2DhyQmeC/tVozIC66U+x6IqmlCsvTLDk6dl0tUD/5YwXC5BdCBvsgkx6qCcBeIXFbgg/1POtv9YYGA8Fs+I9Q6bSYPU8UnwEUZC+Ko3SQh02Z3zuRvNvbcXNV7880TzXJAsVgd0SnQ/CSrxt6lTyjA9qscgR0AsulC8IyFejoSSUnbVgUTgJDnrc4i1YQRxOcv5RZDmHArUZv/Dgfgm72qoLQ1M3b23KNIrSTWvJZ0yJEy0toVyLZIS/ToxcWrtZhjkABQaEw7qm9MLcVE/4D2VpvCJMj0VzUn11OPUu1GqwDa+OsPOGKSqX8l0IonO0SbR9FQSRbQ/9Vrw++bSGenpZPi9wKoSw8ghHNHoMvNm1TKm/pKhTOpDrY/NYXU99MOjg8PohyzFtzc6B5eDtUPpstt5TywRb+aX+1jvYaztk0nq3oeEtyvG6/Sb4xKR8GL5WpCIHD2CYh6B8DpF2xM4b0XtndU71e5kIx8/8elIKpP8aKkK+UELAA3aHiIP+RWCkz++Gt4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
